name: Sync Fork and Rename

on:
  push:
  schedule:
    - cron: '2 */2 * * *'

jobs:
  repo-sync-and-rename:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 设置 Git 用户身份
        run: |
          git config --global user.email "hjchjchjc4352@outlook.com"
          git config --global user.name "hjchjchjc4352"
        working-directory: ${{ github.workspace }}

      - name: 添加上游仓库为远程仓库
        run: git remote add upstream https://github.com/snakem982/proxypool.git
        working-directory: ${{ github.workspace }}

      - name: 获取上游仓库的更新
        run: git fetch upstream
        working-directory: ${{ github.workspace }}

      - name: 合并上游仓库的更新到本地主分支
        run: git merge --allow-unrelated-histories --strategy-option=theirs upstream/main -m "Merge upstream/main"
        working-directory: ${{ github.workspace }}

      - name: 强制更新
        run: git pull --force
        working-directory: ${{ github.workspace }}

      - name: 重命名 clash.yaml 文件
        run: |
          mv -f clash*.yaml clash.yaml
        working-directory: ${{ github.workspace }}

      - name: 重命名 v2ray.txt 文件
        run: |
          mv -f v2ray*.txt v2ray.txt
        working-directory: ${{ github.workspace }}

      - name: 提交并强制推送更改
        run: |
          ls -la
          git add .
          git commit -m "Optimize file names"
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
