name: Sync Fork and Overwrite

on:
  push:
  schedule:
    - cron: '2 */2 * * *'

jobs:
  repo-sync-and-overwrite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Sync with upstream
        uses: TG908/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: snakem982
          head: main
          base: main

      - name: Delete existing one.yaml
        run: |
          rm -f one.yaml
        working-directory: ${{ github.workspace }}

      - name: Overwrite one.yaml
        run: |
          # 获取所有以 "clash" 开头的 YAML 文件
          files=$(ls clash*.yaml)

          # 创建一个新的 one.yaml 文件
          echo "" > one.yaml

          # 循环遍历文件并将内容覆盖到 one.yaml
          for file in $files; do
            cat "$file" > one.yaml
          done
        working-directory: ${{ github.workspace }}

      - name: Commit and push changes
        run: |
          # 添加 one.yaml 文件到 Git
          git add one.yaml
          git config --local user.email "hjchjchjc4352@outlook.com"
          git config --local user.name "hjchjchjc4352"
          git commit -m "Overwrite one.yaml with clash*.yaml files"
          git push --set-upstream origin main
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
