name: Sync Fork and Rename

on:
  push:
  schedule:
    - cron: '* */2 * * *'

jobs:
  repo-sync-and-rename:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync with upstream
        uses: TG908/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: snakem982
          head: main
          base: main

      - name: Rename files
        run: |
          # 在这里编写脚本来动态识别并重命名文件
          # 以下是一个简单的示例，你可能需要根据实际情况修改

          # 获取所有文件名
          files=$(ls *.yaml)

          # 循环遍历文件名
          for file in $files; do
            # 判断文件名是否包含某个字符串（可根据实际情况修改判断条件）
            if [[ $file == *clash* ]]; then
              # 重命名文件为 clash.yaml
              mv "$file" "clash.yaml"
            fi
          done
        working-directory: ${{ github.workspace }}

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Rename files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
