# .github/workflows/sync.yml
name: Scheduled Sync and Rename

on:
  schedule:
    - cron: '* */1 * * *'  # 每1小时触发

jobs:
  sync_and_rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync with upstream
      run: |
        git remote add upstream https://github.com/snakem982/proxypool.git
        git fetch upstream
        git merge upstream/main  # 使用正确的分支名

        # 如果有冲突，可以在此解决冲突，然后提交更改

        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Rename file
      run: |
        # 在这里编写脚本来动态识别并重命名文件
        # 以下是一个简单的示例，你可能需要根据实际情况修改

        # 获取所有文件名
        files=$(ls *.yaml)

        # 循环遍历文件名
        for file in $files; do
          # 判断文件名是否包含某个字符串（可根据实际情况修改判断条件）
          if [[ $file == *clash* ]]; then
            # 重命名文件为 clash.yaml
            mv "$file" "clash.yaml"
          fi
        done
      working-directory: ${{ github.workspace }}
