name: Sync Fork and Rename

on:
  push:
  schedule:
    - cron: '40 1/2 * * *'

jobs:
  repo-sync-and-rename:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 设置 Git 用户身份
        run: |
          git config --global user.email "hjchjchjc4352@outlook.com"
          git config --global user.name "hjchjchjc4352"
        working-directory: ${{ github.workspace }}

      - name: 添加上游仓库为远程仓库
        run: git remote add upstream https://github.com/snakem982/proxypool.git
        working-directory: ${{ github.workspace }}

      - name: 获取上游仓库的更新
        run: git fetch upstream
        working-directory: ${{ github.workspace }}

      - name: 合并上游仓库的更新到本地主分支
        run: git merge --allow-unrelated-histories --strategy-option=theirs upstream/main -m "Merge upstream/main"
        working-directory: ${{ github.workspace }}

      - name: 强制更新
        run: git pull --force
        working-directory: ${{ github.workspace }}

      - name: 重命名文件
        run: |
          # 获取所有文件名
          files=$(ls)

          # 循环遍历文件名
          for file in $files; do
            # 判断文件名是否为 "clash.yaml"
            if [ "$file" != "clash.yaml" ] && [[ $file == clash*.yaml ]]; then
              # 生成新的文件名 clash.yaml
              new_name="clash.yaml"
              # 重命名文件，使用相对路径
              mv "$file" "./$new_name"
            fi

            # 判断文件名是否为 "v2ray.txt"
            if [[ $file == v2ray*.txt && $file != "v2ray.txt" ]]; then
              # 生成新的文件名 v2ray.txt
              new_name="v2ray.txt"
              # 重命名文件，使用相对路径
              mv "$file" "./$new_name"
            fi
          done
        working-directory: ${{ github.workspace }}

      - name: 提交并强制推送更改
        run: |
          ls -la
          git add .
          git commit -m "Optimize file names"
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
