name: Scheduled Sync and Rename

on:
  schedule:
    - cron: '* * * * *'  # 设置定时，这里表示每两小时执行一次同步

jobs:
  sync_and_rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main  # 指定要检出的分支

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge with upstream
      run: git merge --allow-unrelated-histories upstream/main  # 使用正确的分支名

    - name: Push changes
      run: git push origin main

    - name: Rename files
      run: |
        # 在这里编写脚本来动态识别并重命名文件
        # 以下是一个简单的示例，你可能需要根据实际情况修改

        # 获取所有文件名
        files=$(ls *.yaml)

        # 循环遍历文件名
        for file in $files; do
          # 判断文件名是否包含某个字符串（可根据实际情况修改判断条件）
          if [[ $file == *clash* ]]; then
            # 重命名文件为 clash.yaml
            mv "$file" "clash.yaml"
          fi
        done

    - name: Push changes after renaming
      run: git push origin main
