name: Sync Fork and Rename

on:
  push:
  schedule:
    - cron: '2 */1 * * *'

jobs:
  repo-sync-and-rename:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: 设置 Git 用户身份
        run: |
          git config --global user.email "hjchjchjc4352@outlook.com"
          git config --global user.name "hjchjchjc4352"
        working-directory: ${{ github.workspace }}

      - name: 创建临时分支
        run: git checkout -b temp-branch
        working-directory: ${{ github.workspace }}

      - name: 添加上游仓库为远程仓库
        run: git remote add upstream https://github.com/snakem982/proxypool.git
        working-directory: ${{ github.workspace }}

      - name: 获取上游仓库的更新
        run: git fetch upstream
        working-directory: ${{ github.workspace }}

      - name: 合并上游仓库的更新到本地分支
        run: git merge upstream/main --allow-unrelated-histories -m "Merge upstream/main"
        working-directory: ${{ github.workspace }}

      - name: 推送本地分支的更改到远程仓库
        run: git push
        working-directory: ${{ github.workspace }}

      - name: 重命名文件
        run: |
          # 在这里编写脚本来动态识别并重命名文件
          # 以下是一个简单的示例，你可能需要根据实际情况修改

          # 获取所有文件名
          files=$(ls clash*.yaml)

          # 循环遍历文件名
          for file in $files; do
            # 判断文件名是否为 "clash.yaml"
            if [ "$file" != "clash.yaml" ]; then
              # 生成新的文件名 clash.yaml
              new_name="clash.yaml"
              # 重命名文件，使用相对路径
              mv "$file" "./$new_name"
            fi
          done
        working-directory: ${{ github.workspace }}

      - name: 提交并强制推送更改
        run: |
          # 获取当前目录下的文件列表
          ls -la

          # 添加所有更改到 Git
          git add .
          git commit -m "Rename files"
          git push --force --set-upstream origin temp-branch
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}

      - name: 删除主分支
        run: git push --delete origin main
        working-directory: ${{ github.workspace }}
