name: Scheduled Sync and Rename

on:
  schedule:
    - cron: '0 */2 * * *'  # 设置定时，这里表示每两小时执行一次同步

jobs:
  sync_and_rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a new branch
      run: |
        git checkout -b merge-branch
        git remote add upstream --allow-unrelated-histories https://github.com/snakem982/proxypool.git
        git fetch upstream
        git merge --allow-unrelated-histories upstream/main  # 使用正确的分支名

        # 如果有冲突，可以在此解决冲突，然后提交更改

        git push origin merge-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge new branch into main
      run: |
        git checkout main
        git pull origin merge-branch
        git merge merge-branch

        # 如果有冲突，可以在此解决冲突，然后提交更改

        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete the temporary branch
      run: |
        git branch -d merge-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
